<?php

/**
 * Create node tables.
 */
function multiple_db_update_8801()
{
  \Drupal\Core\Database\Database::setActiveConnection('second_db');

  $database = \Drupal\Core\Database\Database::getConnection('second_db');
  $schema = $database->schema();

  require_once __DIR__ . '/includes/db_schema.inc';

  foreach ($tables as $tableName => $table) {
    $schema->createTable($tableName, $table);
  }

  \Drupal\Core\Database\Database::setActiveConnection();
}
