<?php

/**
 * Implements hook_entity_type_alter().
 */
function multiple_db_entity_type_alter(array &$entity_types)
{
  $entity_types['node']->setHandlerClass('storage', 'Drupal\multiple_db\NodeStorage');
}

/**
 * Drop tables.
 */
function drop_database_tables()
{
  \Drupal\Core\Database\Database::setActiveConnection('second_db');

  $database = \Drupal\Core\Database\Database::getConnection('second_db')->schema();

  require_once __DIR__ . '/includes/db_schema.inc';

  $tables = array_keys($tables);

  foreach ($tables as $table) {
    $database->dropTable($table);
  }

  \Drupal\Core\Database\Database::setActiveConnection();

  echo "Dropped second_db node tables";
}
